BEGIN;
--
-- Create model Category
--
CREATE TABLE "core_category" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(200) NOT NULL UNIQUE);
--
-- Create model Manufacturer
--
CREATE TABLE "core_manufacturer" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(200) NOT NULL UNIQUE);
--
-- Create model OrderStatus
--
CREATE TABLE "core_orderstatus" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(50) NOT NULL UNIQUE);
--
-- Create model PickupPoint
--
CREATE TABLE "core_pickuppoint" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "address" text NOT NULL);
--
-- Create model Role
--
CREATE TABLE "core_role" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(50) NOT NULL UNIQUE);
--
-- Create model Supplier
--
CREATE TABLE "core_supplier" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(200) NOT NULL UNIQUE);
--
-- Create model Unit
--
CREATE TABLE "core_unit" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(20) NOT NULL UNIQUE);
--
-- Create model User
--
CREATE TABLE "core_user" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "password" varchar(128) NOT NULL, "last_login" timestamp with time zone NULL, "is_superuser" boolean NOT NULL, "username" varchar(150) NOT NULL UNIQUE, "first_name" varchar(150) NOT NULL, "last_name" varchar(150) NOT NULL, "email" varchar(254) NOT NULL, "is_staff" boolean NOT NULL, "is_active" boolean NOT NULL, "date_joined" timestamp with time zone NOT NULL, "patronymic" varchar(150) NOT NULL, "role_id" bigint NULL);
CREATE TABLE "core_user_groups" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" bigint NOT NULL, "group_id" integer NOT NULL);
CREATE TABLE "core_user_user_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" bigint NOT NULL, "permission_id" integer NOT NULL);
--
-- Create model Order
--
CREATE TABLE "core_order" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "order_date" date NOT NULL, "delivery_date" date NOT NULL, "pickup_code" integer NOT NULL, "user_id" bigint NULL, "status_id" bigint NOT NULL, "pickup_point_id" bigint NOT NULL);
--
-- Create model Product
--
CREATE TABLE "core_product" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "article" varchar(50) NOT NULL UNIQUE, "name" varchar(255) NOT NULL, "price" numeric(10, 2) NOT NULL, "discount" numeric(5, 2) NOT NULL, "quantity" integer NOT NULL, "description" text NOT NULL, "photo" varchar(100) NULL, "category_id" bigint NOT NULL, "manufacturer_id" bigint NOT NULL, "supplier_id" bigint NOT NULL, "unit_id" bigint NOT NULL);
--
-- Create model OrderItem
--
CREATE TABLE "core_orderitem" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "count" integer NOT NULL, "order_id" bigint NOT NULL, "product_id" bigint NOT NULL);
CREATE INDEX "core_category_name_55b68161_like" ON "core_category" ("name" varchar_pattern_ops);
CREATE INDEX "core_manufacturer_name_24f3fcf9_like" ON "core_manufacturer" ("name" varchar_pattern_ops);
CREATE INDEX "core_orderstatus_name_5300284d_like" ON "core_orderstatus" ("name" varchar_pattern_ops);
CREATE INDEX "core_role_name_ca4cd9c7_like" ON "core_role" ("name" varchar_pattern_ops);
CREATE INDEX "core_supplier_name_42c1de63_like" ON "core_supplier" ("name" varchar_pattern_ops);
CREATE INDEX "core_unit_name_8e5279bb_like" ON "core_unit" ("name" varchar_pattern_ops);
ALTER TABLE "core_user" ADD CONSTRAINT "core_user_role_id_8de62872_fk_core_role_id" FOREIGN KEY ("role_id") REFERENCES "core_role" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_user_username_36e4f7f7_like" ON "core_user" ("username" varchar_pattern_ops);
CREATE INDEX "core_user_role_id_8de62872" ON "core_user" ("role_id");
ALTER TABLE "core_user_groups" ADD CONSTRAINT "core_user_groups_user_id_group_id_c82fcad1_uniq" UNIQUE ("user_id", "group_id");
ALTER TABLE "core_user_groups" ADD CONSTRAINT "core_user_groups_user_id_70b4d9b8_fk_core_user_id" FOREIGN KEY ("user_id") REFERENCES "core_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "core_user_groups" ADD CONSTRAINT "core_user_groups_group_id_fe8c697f_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_user_groups_user_id_70b4d9b8" ON "core_user_groups" ("user_id");
CREATE INDEX "core_user_groups_group_id_fe8c697f" ON "core_user_groups" ("group_id");
ALTER TABLE "core_user_user_permissions" ADD CONSTRAINT "core_user_user_permissions_user_id_permission_id_73ea0daa_uniq" UNIQUE ("user_id", "permission_id");
ALTER TABLE "core_user_user_permissions" ADD CONSTRAINT "core_user_user_permissions_user_id_085123d3_fk_core_user_id" FOREIGN KEY ("user_id") REFERENCES "core_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "core_user_user_permissions" ADD CONSTRAINT "core_user_user_permi_permission_id_35ccf601_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_user_user_permissions_user_id_085123d3" ON "core_user_user_permissions" ("user_id");
CREATE INDEX "core_user_user_permissions_permission_id_35ccf601" ON "core_user_user_permissions" ("permission_id");
ALTER TABLE "core_order" ADD CONSTRAINT "core_order_user_id_b03bbffd_fk_core_user_id" FOREIGN KEY ("user_id") REFERENCES "core_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "core_order" ADD CONSTRAINT "core_order_status_id_548839a0_fk_core_orderstatus_id" FOREIGN KEY ("status_id") REFERENCES "core_orderstatus" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "core_order" ADD CONSTRAINT "core_order_pickup_point_id_a5e2e98b_fk_core_pickuppoint_id" FOREIGN KEY ("pickup_point_id") REFERENCES "core_pickuppoint" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_order_user_id_b03bbffd" ON "core_order" ("user_id");
CREATE INDEX "core_order_status_id_548839a0" ON "core_order" ("status_id");
CREATE INDEX "core_order_pickup_point_id_a5e2e98b" ON "core_order" ("pickup_point_id");
ALTER TABLE "core_product" ADD CONSTRAINT "core_product_category_id_b9d8ff9f_fk_core_category_id" FOREIGN KEY ("category_id") REFERENCES "core_category" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "core_product" ADD CONSTRAINT "core_product_manufacturer_id_d625b069_fk_core_manufacturer_id" FOREIGN KEY ("manufacturer_id") REFERENCES "core_manufacturer" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "core_product" ADD CONSTRAINT "core_product_supplier_id_493af3ba_fk_core_supplier_id" FOREIGN KEY ("supplier_id") REFERENCES "core_supplier" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "core_product" ADD CONSTRAINT "core_product_unit_id_9efe97b9_fk_core_unit_id" FOREIGN KEY ("unit_id") REFERENCES "core_unit" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_product_article_5977a5fc_like" ON "core_product" ("article" varchar_pattern_ops);
CREATE INDEX "core_product_category_id_b9d8ff9f" ON "core_product" ("category_id");
CREATE INDEX "core_product_manufacturer_id_d625b069" ON "core_product" ("manufacturer_id");
CREATE INDEX "core_product_supplier_id_493af3ba" ON "core_product" ("supplier_id");
CREATE INDEX "core_product_unit_id_9efe97b9" ON "core_product" ("unit_id");
ALTER TABLE "core_orderitem" ADD CONSTRAINT "core_orderitem_order_id_30929c10_fk_core_order_id" FOREIGN KEY ("order_id") REFERENCES "core_order" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "core_orderitem" ADD CONSTRAINT "core_orderitem_product_id_0c2047cd_fk_core_product_id" FOREIGN KEY ("product_id") REFERENCES "core_product" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_orderitem_order_id_30929c10" ON "core_orderitem" ("order_id");
CREATE INDEX "core_orderitem_product_id_0c2047cd" ON "core_orderitem" ("product_id");
COMMIT;
